id: P000460
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN641
  title: དཔལ་སྤུངས་ཆོས་སྤྱོད།
  author: ''
  volumes:
    a7f7f9199f284baa8336ad2a7d828c2e:
      image_group_id: I3CN643
      title: Volume 1 of dpal spungs chos spyod/
      volume_number: 1
      total_pages: 588
      base_file: v001.txt
